// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: task.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "task";

export interface Task {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  createdBy: string;
  createdAt: string;
}

export interface CreateTaskRequest {
  title: string;
  description: string;
  createdBy: string;
}

export interface GetTaskByIdRequest {
  id: string;
}

export interface UpdateTaskRequest {
  id: string;
  title: string;
  description: string;
  completed: boolean;
}

export interface DeleteTaskRequest {
  id: string;
}

export interface TaskResponse {
  task: Task | undefined;
}

export interface TaskListResponse {
  tasks: Task[];
}

export interface DeleteTaskResponse {
  success: boolean;
}

export interface Empty {
}

export interface CompleteTaskRequest {
  id: string;
}

export const TASK_PACKAGE_NAME = "task";

export interface TaskServiceClient {
  createTask(request: CreateTaskRequest): Observable<TaskResponse>;

  getTaskById(request: GetTaskByIdRequest): Observable<TaskResponse>;

  getAllTasks(request: Empty): Observable<TaskListResponse>;

  updateTask(request: UpdateTaskRequest): Observable<TaskResponse>;

  deleteTask(request: DeleteTaskRequest): Observable<DeleteTaskResponse>;

  completeTask(request: CompleteTaskRequest): Observable<TaskResponse>;
}

export interface TaskServiceController {
  createTask(request: CreateTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  getTaskById(request: GetTaskByIdRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  getAllTasks(request: Empty): Promise<TaskListResponse> | Observable<TaskListResponse> | TaskListResponse;

  updateTask(request: UpdateTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;

  deleteTask(
    request: DeleteTaskRequest,
  ): Promise<DeleteTaskResponse> | Observable<DeleteTaskResponse> | DeleteTaskResponse;

  completeTask(request: CompleteTaskRequest): Promise<TaskResponse> | Observable<TaskResponse> | TaskResponse;
}

export function TaskServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createTask",
      "getTaskById",
      "getAllTasks",
      "updateTask",
      "deleteTask",
      "completeTask",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TaskService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TASK_SERVICE_NAME = "TaskService";
